#!/bin/bash

echo "🚀 启动 LuckyPocket 开发环境"
echo "================================"
echo ""
echo "📋 端口配置:"
echo "   API 后端: http://localhost:9001"
echo "   Web 前端: http://localhost:9002"
echo ""
echo "⚠️  注意: 端口 9000 已被 HKD 项目占用"
echo ""
echo "请在两个终端分别运行以下命令:"
echo ""
echo "📡 终端 1 - API 后端:"
echo "   cd apps/api && pnpm dev"
echo ""
echo "🌐 终端 2 - Web 前端:"
echo "   cd apps/web && pnpm dev"
echo ""
echo "================================"
